### ISSUE TITLE
Safely Disabling the plugin

### ISSUE THREAD

**Issue by cleyda** [bluehost/endurance-page-cache#11]
What is the best way to properly (and safely) disable the plugin? For example, it does not seem that disabling the plugin restores the htaccess file (e.g. the mod rewrites that redirect to the cache are not removed). 

This might mean that if the plugin is disabled, htaccess will continue to direct traffic to the cached pages (which may not be monitored for updates, now that the plugin is disabled).

Also, if the server detects that no endurance page cache plugin is running, won't it just reinstall the plugin and fire it up?

**Comment by lukecav** [comment]
You can just manually write out the default WP htaccess code into the site .htaccess file.

`# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress`

[https://codex.wordpress.org/htaccess](url)

**Comment by Johan333g** [comment]
DO NOT ACTIVATE THIS PLUGIN delete the file mu-plugins/endurance-page-cache.php from your install using an FTP manager.. Then install a real caching plugin.

The disable is not working for you because the files are directed by the .php DO NOT ATTEMPT to rewrite your access file unless necessary

**Comment by senordeer** [comment]
I have had this issue with some blogs that get an error string when someone tries to post a comment.  I followed Johan's steps to delete the file.  Just chiming in, Bluehost should be aware of this conflict with Wordpress.  Annoying!

**Comment by MikeHansenMe** [comment]
@senordeer this is a known issue and we will be releasing an update very soon to get it corrected. The fix ( https://github.com/bluehost/endurance-page-cache/commit/fefa98c4ddd41cc860967b3197f139950c797bd0 )is currently in the master branch.

Thank you for letting us know. If you have any other bugs, please do not hesitate to let us know. We want to get the bugs corrected.

**Comment by senordeer** [comment]
Hey Mike, fantastic, it's only recently I have had people complain.  Good to hear, I will remain a happy Bluehost affiliate seller :)

**Comment by Johan333g** [comment]
The solution I used above was just temporary to update and get the sites functional enough to be usable.

This plugin has been causing multiple issues with sites for a while now, without disabling the plugin after purging all cache first the site becomes unusable for the administrator, no longer updated pages and posts correctly; even after removal I had to log out of the site and then back in to avoid http upload errors when adding products to commerce sites. 

The servers at hostgator are running some very outdated software and the "known issues" seem to be more prevalent than on bluehost. 

I have since had to remove all sites that I have with hostgator and bluehost and any other Endurance servers to private servers at considerable expense of time and money. 

An expense that could have been avoided, had this plugin not been installed into WordPress without consent and then re-installed once deleted.

I will no longer be recommending or using hostgator, bluehost or any Endurance owned hosting company. There is a definite difference between cheap and worthless, they used to be cheap and now they are worthless.

Deploying software with "known issues", is irresponsible at the very least. Disrupting commerce online, is illegal at the very least. Taking claim and describing your own product as having "known issues" and continuing to force its use, is at the very least criminally negligent.. but, I suppose that is up to a federal/state prosecutor to decide.

**Comment by goldtreefrog** [comment]
Amen to the complaints above.

I have lost trust in BlueHost because BlueHost did NOT notify webmasters that this plugin would be installed. 

Also, I have a related issue I bring up because even if we do something about the WordPress caching issue, BlueHost seems to cache other files without our knowledge or consent. Yesterday I ran into an apparent server-side caching issue on a STATIC HTML page in a subfolder of my root account folder, neither of which use WordPress or PHP. What gives? I was making changes to one particular HTML page and uploading it several times in a row (because I kept thinking I was finished and then kept seeing one more minor thing to change ;-). What convinced me that it was a server-side issue was when I opened the same page in a browser I had never opened it in before - the page had only been uploaded the first time that very day (yesterday) - and the OLD page showed in that browser too. This is NOT a heavily-visited area; in fact the subfolder was only created that day too. Diagnosing the caching issue here wasted 20 minutes. 

My user wasted an hour of both of our times a couple of days ago after he tried to make a page update and could not see the update live in production. Then I wasted another hour trying to figure out why the www.___.com version of the website was now showing the current page while the http://___.com version (no 'www') was still showing the old page. I fixed that with a redirection, but it did not really fix the server-side caching problem. So yesterday I spent another hour researching BlueHost and server-side caching. There are a number of unhappy web hosts because of this. You will find them if you Google the issue.

I have nothing against caching in principle - in fact I use Cloudflare for two of my sites and I see that the Endurance plug-ins have been unnecessarily been installed on those two sites, too! 

Today I am searching for an ethical webhost who practices transparency. Had I KNOWN about the plug-ins from the beginning, I would have saved my user and me a total of over 4 hours. If I actually had PAID clients, the situation would be even worse. I will be soliciting paid clients in the future, and I want to be sure to be using a webhost I can trust when I do so.

**Comment by hanasazi** [comment]
Most of the sites I work on where EPC is installed seem to be working okay, but I'm having terrible problem on one. It's causing PHP errors like this: Invalid arguments passed in /home2/cathesn4/public_html/wp-content/mu-plugins/endurance-page-cache.php on line 462 (this error showed up on July 1, 8 and 19). The thing is that the site is not accessible by everyone. The owner is an artist and is about to have a show of her work, so she needs the site to operate properly, yet the lady who owns the gallery where she will be showing next month cannot access her site at all and wrote me to say that it was down. I went to check it and it was fine for me. The owner herself cannot access her site either. I'm going to disable it now and see if that improves the situation at all.

**Comment by Nodws** [comment]
Horrible practice, just went ahead and cancelled all known bluehost accounts in our company (20+)

**Comment by diurchenko** [comment]
4 hours wasted on attempts to get rid of "Generated by Endurance Page Cache". This is a disease, not a plugin. I have removed everything from every corner of each menu, removed it from mu-plugins folder, purged every possible cache… still can't see the root page of my website. sick 🤯

**Comment by hhuesca** [comment]
Fuck you and your plugin!

**Comment by rylanb** [comment]
This plugin is the worst. Blocks other plugins from loading assets, you delete it, doesn't clear out and fix any issues. Terrible practice.

**Comment by earnjam** [comment]
If you don't want to have this caching enabled, you can change it in the WordPress admin under Bluehost > Performance (if you have the Bluehost plugin active), or under Settings in the Endurance Cache section by choosing `Off (Level 0)` from the select input. 

Once disabled, you can remove the mu-plugin, or just leave it, as it does nothing at that point. 

If you are still having problems, please feel free to add a comment or open a new issue. We're working on some major improvements to the plugin and we'd love to get any issues resolved.
