### ISSUE TITLE
Endurance-Page-Cache Force Reinstalling Itself on All My Sites

### ISSUE THREAD

**Issue by DabidK** [bluehost/endurance-page-cache#12]
A couple weeks ago I was having problems where Endurance-Page-Cache had been installed across all my domains by Bluehost without my knowledge or permission, causing me to have thousands of unwanted directories and get warnings from BlueHost about exceeding my directory quote. Mike Hansen was nice enough to get the plugins removed for me and I thought the problem was solved.

Unfortunately, I logged into BlueHost today to find out that Endurance-Page-Cache **IS BACK** and I'm getting the same warning from BlueHost: _"Your account contains more than 9740 directories and may pose a potential performance risk to the server.<br>Please reduce the number of directories for your account to prevent <em>possible</em> account deactivation."_ I don't appreciate getting these threatening warnings when BlueHost is reinstalling things I've already had to go out of my way to uninstall that I never wanted in the first place!

I do not want Endurance-Page-Cache on any of my sites ever. I want it gone. I'm not a programmer and I don't know anything about rewriting .htaccess for anything like that. What do I need to do to have this removed from toyreviewdaily.com and all of its subdomains again and to ensure that it NEVER comes back? I already have a Cloud Business Pro account -and- CloudFlare enabled. I don't need or want Endurance-Page-Cache and I don't want to see it again. Help me please?

**Comment by MikeHansenMe** [comment]
Hey Dabid, like I mentioned in the email response. This was added to your site because it(your account) is using a lot of resources. Normally the file count for an average website is not not a problem but looking at your account it looks like there is a number of sites. I removed the plugin and updated the htaccess file on your primary domain. Please contact tech-support if you have any further questions.
