### ISSUE TITLE
Need to have control over this plugin

### ISSUE THREAD

**Issue by sangemaru** [bluehost/endurance-page-cache#13]
We need to be aware when this plugin is installed (notification inside the WP admin area) as well as have control over cache purging. Otherwise (as I see from the other issue threads) lots of users are going to be wasting lots of hours troubleshooting isses with their websites without realizing the trouble lies with a plugin automatically installed by bluehost without our knowledge and permission.

**Comment by MikeHansenMe** [comment]
Hey @sangemaru thank you for your feedback. We do need to find a way to better communicate when this is added to a site. We are working to make the purging as accurate and automatic as possible. There should be a purge button on the plugin page that you can "purge all". In fact the primary purpose of this plugin (besides the performance gains) are to get the purging right because we want to have it purge all the caching layers. All of the code has been written in a way that all the expirations can be changed. If you run the MOJO Marketplace plugin there is also a Performance page that will allow you to enable/disable the caching features.
