### ISSUE TITLE
No way to clear cache

### ISSUE THREAD

**Issue by wesbos** [bluehost/endurance-page-cache#20]
Is bluehost enabling this plugin without my permission? Not cool at all.

Just wasted an hour trying to figure out why my permalink changes were not being affected. 

How do I disable this for bluehost?

**Comment by MikeHansenMe** [comment]
hey @wesbos can you give me a domain? There should be both a clear cache button & it should automatically be fired on a permalink change. If this is not happening, I would love to dig in and find out what is going on.

**Comment by earnjam** [comment]
@wesbos It's been almost 2 years since you opened this, but I wanted to check in to see if ever got this resolved? It should be clearing on permalink changes, so if it isn't happening for some reason that would be a bug we'd love to get fixed. 

That said, if you don't want to have this caching enabled, you can change it in the WordPress admin under Bluehost > Performance (if you have the Bluehost plugin active), or under Settings in the Endurance Cache section by choosing Off (Level 0) from the select input.

Once disabled, you can remove the mu-plugin, or just leave it, as it does nothing at that point.

**Comment by wesbos** [comment]
@earnjam you need to document this on this github repo

**Comment by earnjam** [comment]
@wesbos Thanks. Doing some work on the plugin, so will add some GitHub documentation to the list. 

I'm going to close this since it seems like the original issue is resolved. If you're still having trouble, please let us know.
