### ISSUE TITLE
Upgrade endurance cache

### ISSUE THREAD

**Issue by jlb30504** [bluehost/endurance-page-cache#23]
@MikeHansenMe What is the best way to upgrade the endurance cache for www.tngenweb.org?  We currently have 0.2 of the page cache and no way to turn cache off and no purge button.  I called Bluehost support and they said to just copy the two files from a later Bluehost site.  I am nervous about doing that.  Please confirm this approach is OK.  Thanks.

**Comment by MikeHansenMe** [comment]
I will get it updated for you. 0.2 is really old. In the future you will
not need to update it, it will update itself.

On Jun 17, 2017 2:05 PM, "jlb30504" <notifications@github.com> wrote:

@MikeHansenMe <https://github.com/mikehansenme> What is the best way to
upgrade the endurance cache for www.tngenweb.org? We currently have 0.2 of
the page cache and no way to turn cache off and no purge button. I called
Bluehost support and they said to just copy the two files from a later
Bluehost site. I am nervous about doing that. Please confirm this approach
is OK. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bluehost/endurance-page-cache/issues/23>, or mute the
thread

**Comment by jlb30504** [comment]
@MikeHansenMe Thanks for getting the endurance cache upgraded for www.tngenweb.org.  I see cache files coming and going but the lifetime seems very short.  I see cache enteries going away after just a few seconds.  Is this normal?

**Comment by MikeHansenMe** [comment]
It depends. Basically the way it works is you have some settings on the Settings -> General page that allow you to set how aggressive you want the max life to be. The only difference between the top 3 levels is duration. However the main thing the plugin does is actually purge the cache on specific actions to ensure it is fresh if anything has changed. There are times when a plugin or cron on your site are changing settings and causing these extra purges to happen. I would try upping the setting to a more aggressive level and then keep an eye on it. If is continues to purge too frequently, I can look into it and see what is triggering it.

**Comment by jlb30504** [comment]
@MikeHansenMe I changed the setting on the cache to the most aggressive level but nothing has changed.  Since the upgrade, I am showing only 5 or 10 inodes in endurance-page-cache.  There were more than 10,000 pages cached in the same time frame with the 0.2 version of the cache.  Can you please look into why the cache isn't working for www.tngenweb.org?

**Comment by MikeHansenMe** [comment]
@jlb30504 can you send me an email to mike.hansen [a] endurance.com? The newer versions of the plugin are more selective in what they cache but there are a few tweaks we can make to get it working really well.

**Comment by Johan333g** [comment]
DO NOT ACTIVATE THIS PLUGIN delete the file mu-plugins/endurance-page-cache.php from your install using an FTP manager.. Then install a real caching plugin that doesn't break your site.
