### ISSUE TITLE
Please stop that plugin auto-installing!!

### ISSUE THREAD

**Issue by omrb** [bluehost/endurance-page-cache#58]
Your auto-installing must-use plugin(!) crashes my little blog and i am tired of cleaning the mess it creates. Please stop auto-installing!!!

**Comment by earnjam** [comment]
This plugin is required in order to handle cache purging. Without it, your site will not be able to clear the edge cache and your content will not update right away after being edited. 

I'd be curious to understand what about the plugin is causing your site to crash. That should not be happening. Can you provide any additional details?

**Comment by omrb** [comment]
I uninstalled some older plug-ins and everything acting normal now. Problems solved, thanks!
