### ISSUE TITLE
Unintended caching experience

### ISSUE THREAD

**Issue by rhadiaris** [bluehost/endurance-page-cache#7]
On www.duluthcurlingclub.org, we are noticing the home page is not updating after doing things in the Wordpress admin (like deleting images from news posts).  We are also noticing that highly dynamic pages (like our league pages which have updated scores from matches) are not updating either.  

We did not ask for this plugin.  Can it please be removed so our site behaves as expected, or can these issues be addressed?

**Comment by emgorman** [comment]
My dynamic pages were not getting updated either. 

I was able to remove the plugin by accessing the site via ftp and going to wp-content/mu-plugins and deleting both folders there. You also have to remove the code it wrote to your .htaccess file in the root.

 I can see how it would help make the site faster, and I would be happy to turn it back on once they figure out a way to let me exclude urls/pages or make it so the cache is purged automatically after 24 hours.

**Comment by czenzel** [comment]
I am also having this issue on a client site. the home page will not update at all no mater what I do. It turns out after doing HTTP header diagnosis, because the support guy at BlueHost just randomly disappeared, returned that the X-Proxy cache headers were stale and would not update. I am not running this plugin on the site yet. I would recommend that @bluehost check their reverse proxies and Varnish cache servers. Our site's home page and some of the other pages are not updating. According to the headers, not since Friday.

**Comment by trentontri** [comment]
@bluehost this is creating massive headaches for me too.

**Comment by earnjam** [comment]
I'm going to close this, as it hasn't been updated in > 2 years and I think these issues have been resolved. If you are still having problems, please feel free to add a comment, open a new issue, or open a support ticket. 

If you don't want to have this caching enabled, you can change it in the WordPress admin under Bluehost > Performance (if you have the Bluehost plugin active), or under Settings in the Endurance Cache section by choosing `Off (Level 0)` from the select input.
